### ISSUE TITLE
UU decoding raises an exception in some cases

### ISSUE THREAD

**Issue by RomainJennes** [dhondta/python-codext#4]
```
# cat raw.txt 
1Oh6axLwfecHErbVpRbtNj8t5JACsSQrofdnnMdQtBmoU8cQj6EyLcVRsQLz1MyWfXbqQDIc9wGyyBuH7uV95lBVpFGn3syGIw0IVLx8wJr4ABsIH9Q71hBH4AvIgljx7XnfjfmafahBNrPMDkK3dsJF0r41nzyMnOf7l36NcllAOgRLoB6Qh0APotZu6plYpkSiRCAkDKowOFm0mybKp336TAJe4JiDecD9hNbl5fBDLkGNYhmSkzOQzLBH1aPumW4o

# codext -i raw.txt decode base62
begin 666 <data>
M'XL( /H^)V("__-)SBB-<O7*+#;,K8PL\/ H\C#UR2LP= H)C0@-RZ\*"P@M
M\"T-\*@(#\]V\<A,*R^W\"@I,W9Q-,LU\8XR=$XM*TYR3PG,2G)+RO P#_'.
?"LRJS#)US0X(KPJH<$U.J@P(<TGR  #3A(K<90      
 
end

# codext -i raw.txt decode base62 | codext decode UU
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/uu_codec.py", line 58, in uu_decode
    data = binascii.a2b_uu(s)
binascii.Error: Illegal char

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeane/.local/bin/codext", line 8, in <module>
    sys.exit(main())
  File "/home/jeane/.local/lib/python3.8/site-packages/codext/__init__.py", line 124, in main
    c = getattr(codecs, ["encode", "decode"][args.command == "decode"])(c, encoding, args.errors)
  File "/home/jeane/.local/lib/python3.8/site-packages/codext/__common__.py", line 691, in decode
    return lookup(encoding).decode(obj, errors)[0]
  File "/usr/lib/python3.8/encodings/uu_codec.py", line 62, in uu_decode
    data = binascii.a2b_uu(s[:nbytes])
binascii.Error: Illegal char
```

**Comment by dhondta** [comment]
Hi @RomainJennes 
Thank you for reporting this.

**Problem**: This is issue arises from the native `uu_codec`, which was used by CodExt with no fix.

**Solution**: CodExt's `uu` codec now relies on the `uu` native package and is implemented and tested from version 1.13.2. This was fixed in df8ff0fe870315c15eee63428516b47a1a74628b.
